server:
  port: ${SIDEIMSS_CATALOGOS_PORT}
jwt:
  secret: TExBVkVfTVVZX1NFQ1JFVEzE3Zmxu7BSGSJx72BSBXM 
spring:
  application:
    name: mssideimss-catalogos
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${SIDEIMSS_DB_URL}
    username: ${SIDEIMSS_DB_USER}
    password: ${SIDEIMSS_DB_PASSWORD}
    hikari:
      minimum-idle: ${POOL_MINIMUM_IDLE}
      maximum-pool-size: ${POOL_MAX_SIZE}
      idle-timeout: ${POOL_IDLE_TIMEOUT}
      max-lifetime: ${POOL_LIFETIME}
      connection-timeout: ${POOL_CONNECTION_TIMEOUT}
      pool-name: sideimssPoolCatalogos
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        proc:
          param_null_passing: true
management:
  endpoints:
    web:
      base-path: /mssideimss-catalogos/v1/actuator
      exposure:
        include: health
  endpoint:
    auditevents:
      enabled: true
    
integration:
  sat:
    wsdl-url: ${SIDEIMSS_SAT_WSDL}